const getPublishungContents = [
  {
    id: 1,
    title: "서울시립미술관 메인페이지",
    explain: "소개: 서울시립미술관 반응형 메인페이지 리디자인",
    period: "기간: 디자인 2일, 코딩 4일",
    part: "기여도: 1인 작업",
    tools: [1, 2, 3, 6],
    href: "",
    logo: "",
  },
  {
    id: 2,
    title: "포트폴리오",
    explain: "소개: 반응형 웹 포트폴리오 제작",
    period: "기간: 디자인 4일, 코딩 6일",
    part: "기여도: 1인 작업",
    tools: [1, 2, 3, 4, 5, 6],
    href: "",
    logo: "",
  },
  {
    id: 3,
    title: "디즈니+ 랜딩페이지",
    explain: "소개: 디즈니+ 반응형 랜딩페이지 제작",
    period: "기간: 디자인 1일, 코딩 3일",
    part: "기여도: 1인 작업",
    tools: [1, 2, 3, 4, 5],
    href: "",
    logo: "",
  },
  {
    id: 4,
    title: "트래블월렛 랜딩페이지",
    explain: "소개: 트래블월렛 반응형 랜딩페이지 제작",
    period: "기간: 디자인 1일, 코딩 2일",
    part: "기여도: 1인 작업",
    tools: [1, 2, 4, 5],
    href: "",
    logo: "",
  },
  {
    id: 5,
    title: "에어비앤비 UX개선 팀 프로젝트",
    explain: "소개: 에어비앤비 모바일 웹 리뉴얼",
    period: "기간: 디자인 7일, 코딩 7일",
    part: "기여도: 디자인, 코딩 33%",
    tools: [1, 2, 4, 6],
    href: "",
    logo: "",
  },
  {
    id: 6,
    title: "포터리 메인, 서브페이지 리디자인",
    explain: "소개: 포터리 메인, 서브페이지 리디자인",
    period: "기간: 디자인 2일, 코딩 2일",
    part: "기여도: 1인 작업",
    tools: [1, 2, 4],
    href: "",
    logo: "",
  },
];
